version: '3'
services:
  postgresql:
    image: docker.io/bitnami/postgresql:14.5.0
    ports:
      - '5432:5432'
    volumes:
      - '~/psql_data:/bitnami/postgresql'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres123!'
      - 'POSTGRESQL_DATABASE=mydatabase'

volumes:
  postgresql_data:
    driver: local
  redis_data:
    driver: local
